#!/usr/bin/with-contenv bash

# make our folders
mkdir -p \
    /gallery

# install piwigo
if [ ! -f "/config/www/gallery/index.php" ] && [ ! -f "/gallery/index.php" ]; then
    unzip -q /piwigo/piwigo.zip  -d /tmp
    mv /tmp/piwigo/* /gallery
    rm -rf /tmp/piwigo
fi

# copy config
if [ ! -f "/config/www/gallery/local/config/config.inc.php" ] && [ ! -f "/gallery/local/config/config.inc.php" ]; then
    cp /gallery/include/config_default.inc.php /gallery/local/config/config.inc.php
fi


if [ ! -d "/config/www/gallery" ]; then
    ln -s /gallery /config/www/gallery
fi

if [[ -d /gallery ]]; then
    if [[ "$(stat -c '%U' /gallery)" != "abc" ]]; then
        chown -R abc:abc /gallery
    fi
fi

# permissions
chown -R abc:abc \
    /config

