#!/usr/bin/with-contenv bash

# make our folders
mkdir -p \
    /gallery

# install piwigo
if [ ! -f "/config/www/gallery/index.php" ] && [ ! -f "/gallery/index.php" ]; then
    unzip -q /piwigo/piwigo.zip  -d /tmp
    # NFS volumes and chmod dont mix. We disable the chmods. And we do it later.
    find /tmp/piwigo -type f -name "*.php" -print0 | xargs -0 sed -i -e 's/@\?chmod\s*(/true || chmod(/g'
    mv /tmp/piwigo/* /gallery
    rm -rf /tmp/piwigo
fi

# copy config
if [ ! -f "/config/www/gallery/local/config/config.inc.php" ] && [ ! -f "/gallery/local/config/config.inc.php" ]; then
    cp /gallery/include/config_default.inc.php /gallery/local/config/config.inc.php
fi


if [ ! -d "/config/www/gallery" ]; then
    ln -s /gallery /config/www/gallery
fi

